steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=gcr.io/$PROJECT_ID/helmfile",
        "--build-arg",
        "HELM_VERSION=v3.0.2",
        "--build-arg",
        "HELMFILE_VERSION=v0.97.0",
        ".",
      ]

images: ["gcr.io/$PROJECT_ID/helmfile"]
tags: ["cloud-builders-community"]
