# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=18.16.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:node-18.16.0'
  # 18.16.0 is tagged :latest
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:latest'
  - '--tag=gcr.io/$PROJECT_ID/nodejs/yarn-puppeteer'
  - '.'
# Print for each version
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-18.16.0'
  args: ['--version']

images:
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:latest'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-18.16.0'
- 'gcr.io/$PROJECT_ID/nodejs/yarn-puppeteer'
tags: ['cloud-builders-community']
